# Generated by Django 4.2.1 on 2023-05-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_users_delete_file_alter_files_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.users', verbose_name='Пользователь'),
        ),
    ]
