# Generated by Django 4.2.1 on 2023-05-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_delete_file_alter_users_username'),
    ]

    operations = [

    ]
